export const FormActions = {
  UPDATE_NAME: 'UPDATE_NAME',
  UPDATE_LASTNAME: 'UPDATE_LASTNAME',
  UPDATE_BIRTH: 'UPDATE_BIRTH',
  UPDATE_WEIGHT: 'UPDATE_WEIGHT',
  UPDATE_BELT: 'UPDATE_BELT',
  UPDATE_STRIPE: 'UPDATE_STRIPE'
};
